name: "CI"

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest	

    steps:
      - name: Whatever
        uses: mmisiorek/npmrc@master
        with:
          github_personal_token: reijiowejreiojwrew
          organization_name: mmisiorek

      - name: x
        run: ls -la $HOME && cat $HOME/.npmrc
